#!/usr/bin/perl

# 快速运行x86_64汇编

use v5.26;
use strict;
use utf8;
use autodie;
use warnings;
use Encode qw(decode encode);
use File::Basename;
use File::Spec::Functions qw(catfile); # join path

my $source = shift @ARGV;

if(!defined($source)){
  exit;
}

$source =~ s/\p{space}/\\ /g; # 避免windows上的空格文件

my ($name, $dir, $suffix) = fileparse($source, qr/\.[^.]*/);

if($suffix eq '.asm'){
  my $command1  = "nasm -f elf64 -o $name.o $source";
  my $command2  = "ld $name.o -o $name";
  my $command3  = "./$name";

  system $command1;
  system $command2;
  system $command3;

  # 执行后删除文件
  # unlink("./$name");
  # unlink("./$name.o");
}

