#!/usr/bin/perl

use v5.10;
use strict;
use utf8;
use autodie;
use warnings;
use Encode qw(decode encode);
use experimental 'smartmatch'; # 忽略智能匹配的错误警告

if( defined($ARGV[0]) and -e $ARGV[0] ) {
	system "vim $ARGV[0] -c 'normal! gg=G' -c ':wq!'";
}
