#!/usr/bin/perl

# 快速启动一些npm脚本
# λ anpm -h

use v5.10;
use strict;
use utf8;
use autodie;
use warnings;
use Encode qw(decode encode);
use Data::Dumper qw(Dumper);
use Getopt::Long qw(GetOptions);
use Term::ANSIColor;
use File::Basename;
use Cwd qw(abs_path);
use lib dirname (abs_path(__FILE__));

use PrintHelp;

my $registry_taobao = "https://registry.npm.taobao.org/";
my $registry_npm = "https://registry.npmjs.org/";

my ($help, $publish, $taobao, $npm, $update, $registry, $global, $list);

# 如果运行脚本，一个参数都没有传入，则打印help文档
GetOptions (
	"publish" => \$publish,
	"npm" => \$npm,
	"taobao"   => \$taobao,
	"help"   => \$help,
	"update"   => \$update,
	"registry"  => \$registry,
	"global" => \$global,
	"list" => \$list
);

if(defined($help)){
	PrintHelp->new([ "anpm -h" ],
		{
			publish => {
				msg => "发布npm包，将自动切换到npm源，发布成功后在自动切回taobao源",
			},
			taobao => {
				msg => "设置淘宝源",
				default => $registry_taobao
			},
			npm => {
				msg => "设置默认源",
				default => $registry_npm
			},
			update => {
				msg => "升级package.json的依赖包",
			},
			registry => {
				msg => "查看当前源",
			},
			global => {
				msg => "global -g",
			},
			list => {
				msg => "npm list --depth=0",
			},
			help => {
				msg => "帮助文档.",
			}
		}
		
		);
	exit;
}

sub show_registry {
system 'npm config get registry';
}

# 发布后立即切换回taobao源
if(defined($publish)){
	system 'npm config set registry '. $registry_npm;
	system 'npm publish';
	system 'npm config set registry '. $registry_taobao;
}

if(defined($npm)){
	system 'npm config set registry '.$registry_npm;
	show_registry();
}

if(defined($taobao)){
	system 'npm config set registry '.$registry_taobao;
	show_registry();
}

if(defined($update)){
	system defined($global) ? 'npx npm-check-updates -g' : 'npx npm-check-updates -u && npm i';
}

if(defined($list)){
	system defined($global) ? 'npm -g list --depth=0' : 'npm list --depth=0';
}

if(defined($registry)){
	show_registry();
}
