#!/usr/bin/perl

# 快速切换npm源
# λ npm config get registry
# https://registry.npm.taobao.org/
# λ anpm --npm
# λ npm config get registry
# https://registry.npmjs.org/

use strict;
use utf8;
use autodie;
use warnings;
use Encode qw(decode encode);
use Data::Dumper qw(Dumper);
use Getopt::Long qw(GetOptions);
use Term::ANSIColor;

my $helpTemp = <<"help";

  --publish\t\t自动切换为npm源
  --taobao \t\t设置淘宝源 https://registry.npm.taobao.org/
  --npm    \t\t设置默认源 https://registry.npmjs.org/

help

my $publish;
my $taobao;
my $npm;
my $help;

# 如果运行脚本，一个参数都没有传入，则打印help文档
if(!defined($ARGV[0])){
	print color('green');
  print encode('utf-8', $helpTemp);
  exit;
}

GetOptions (
						"publish" => \$publish,
            "npm" => \$npm,
            "taobao"   => \$taobao,
            "help"   => \$help,
            ) or die("Error in command line arguments\n");

if(defined($help)){
	print color('green');
	print encode('utf-8', $helpTemp);
}

if(defined($publish)){
	system 'npm config set registry https://registry.npmjs.org/';
	system 'npm publish'
}

if(defined($npm)){
	system 'npm config set registry https://registry.npmjs.org/';
}

if(defined($taobao)){
	system 'npm config set registry https://registry.npm.taobao.org/';
}