#!/usr/bin/perl

# [Ajanuw]
# 快速创建一个Webpack的脚手架
# See also:
# https://webpack.js.org/
# https://www.webpackjs.com/
# https://github.com/januwA/webpack-scaffold.git

use v5.26;
use strict;
use utf8;
use autodie;
use warnings;
use Term::ANSIColor;

system 'git clone https://github.com/januwA/webpack-scaffold.git';

my $msg = <<'data';

    See also:

      # https://webpack.js.org/
      # https://www.webpackjs.com/
      # https://github.com/januwA/webpack-scaffold.git

data

# 打印green颜色的字体
print color('green');
print $msg;
